;
; File generated by cc65 v 2.13.3
;
	.fopt		compiler,"cc65 v 2.13.3"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank, tmp1, ptr1, ptr2
	.macpack	longbranch
	.dbg		file, "clibtest.c", 82, 1367476720
	.dbg		file, "../../../include/stdio.h", 5964, 1254052987
	.dbg		file, "../../../include/stddef.h", 2972, 1253259480
	.dbg		file, "../../../include/stdarg.h", 2817, 1102777145
	.forceimport	__STARTUP__
	.import		_printf
	.export		_main

.segment	"RODATA"

L0001:
	.byte	$54,$65,$73,$74,$69,$6E,$67,$20,$43,$4C,$69,$62,$0A,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; printf("Testing CLib\n");
;
	.dbg	line, "clibtest.c", 4
	lda     #<(L0001)
	ldx     #>(L0001)
	jsr     pushax
	ldy     #$02
	jsr     _printf
;
; return 0;
;
	.dbg	line, "clibtest.c", 6
	ldx     #$00
	txa
;
; }
;
	.dbg	line, "clibtest.c", 7
	rts
	.dbg	line

.endproc

