;
; File generated by cc65 v 2.11.0
;
	.fopt		compiler,"cc65 v 2.11.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank, tmp1, ptr1, ptr2
	.macpack	longbranch
	.dbg		file, "closedir.c", 107, 1142525752
	.dbg		file, "/home/dominic/Documents/programming/6502/mysources/cc65-2.11.0/include/dirent.h", 3037, 1142524617
	.dbg		file, "./dir.h", 222, 1142594921
	.export		_closedir

; ---------------------------------------------------------------
; int __fastcall__ closedir (struct DIR*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_closedir

.segment	"CODE"

;
; int __fastcall__ closedir (DIR* dir) {
;
	.dbg	line, "closedir.c", 6
	jsr     pushax
;
; if (dir)
;
	.dbg	line, "closedir.c", 7
	ldy     #$01
	lda     (sp),y
	dey
	ora     (sp),y
	jeq     incsp2
;
; dir->used = 0;
;
	.dbg	line, "closedir.c", 8
	iny
	jsr     ldaxysp
	sta     sreg
	stx     sreg+1
	ldx     #$00
	txa
	ldy     #$0D
	sta     (sreg),y
;
; }
;
	.dbg	line, "closedir.c", 6576816
	jmp     incsp2
	.dbg	line

.endproc

