;
; File generated by cc65 v 2.11.0
;
	.fopt		compiler,"cc65 v 2.11.0"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	on
	.importzp	sp, sreg, regsave, regbank, tmp1, ptr1, ptr2
	.macpack	longbranch
	.dbg		file, "opendir.c", 517, 1142595077
	.dbg		file, "/home/dominic/Documents/programming/6502/mysources/cc65-2.11.0/include/dirent.h", 3037, 1142524617
	.dbg		file, "./dir.h", 222, 1142594921
	.dbg		file, "/home/dominic/Documents/programming/6502/mysources/cc65-2.11.0/include/errno.h", 3690, 1142154975
	.export		_opendir
	.import		__errno
	.export		_dirs

.segment	"BSS"

_dirs:
	.res	70,$00

; ---------------------------------------------------------------
; struct DIR* __fastcall__ opendir (const unsigned char*)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_opendir

.segment	"CODE"

;
; DIR* __fastcall__ opendir (const char* name) {
;
	.dbg	line, "opendir.c", 15
	jsr     pushax
;
; ret = NULL;
;
	.dbg	line, "opendir.c", 22
	jsr     decsp4
	ldx     #$00
	txa
	ldy     #$02
	jsr     staxysp
;
; for (i = 0; i < MAXOPENDIRS; i++) {
;
	.dbg	line, "opendir.c", 23
L0025:	ldy     #$00
	jsr     staxysp
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	lda     #$02
	jsr     toslta0
	beq     L0009
;
; if (dirs[i].used == 0) {
;
	.dbg	line, "opendir.c", 24
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	lda     #$23
	jsr     tosmula0
	clc
	adc     #<(_dirs)
	sta     ptr1
	txa
	adc     #>(_dirs)
	sta     ptr1+1
	ldy     #$0D
	lda     (ptr1),y
	bne     L000A
;
; ret = &dirs[i];
;
	.dbg	line, "opendir.c", 25
	ldy     #$01
	jsr     ldaxysp
	jsr     pushax
	lda     #$23
	jsr     tosmula0
	clc
	adc     #<(_dirs)
	tay
	txa
	adc     #>(_dirs)
	tax
	tya
	ldy     #$02
	jsr     staxysp
;
; for (i = 0; i < MAXOPENDIRS; i++) {
;
	.dbg	line, "opendir.c", 23
L000A:	ldy     #$01
	jsr     ldaxysp
	clc
	adc     #$01
	bcc     L0025
	inx
	jmp     L0025
;
; if (ret == NULL) {
;
	.dbg	line, "opendir.c", 29
L0009:	ldy     #$02
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L0017
;
; _errno = EMFILE;
;
	.dbg	line, "opendir.c", 30
	tax
	lda     #$05
	sta     __errno
	stx     __errno+1
;
; return NULL;
;
	.dbg	line, "opendir.c", 31
	txa
	jmp     incsp6
;
; ret->channel = 0;
;
	.dbg	line, "opendir.c", 34
L0017:	jsr     ldaxysp
	sta     sreg
	stx     sreg+1
	lda     #$00
	tay
	sta     (sreg),y
;
; ret->seq = 0;
;
	.dbg	line, "opendir.c", 35
	ldy     #$05
	jsr     pushwysp
	ldx     #$00
	stx     sreg
	stx     sreg+1
	txa
	ldy     #$09
	jsr     steaxspidx
;
; ret->used = 1;
;
	.dbg	line, "opendir.c", 36
	ldy     #$03
	jsr     ldaxysp
	sta     sreg
	stx     sreg+1
	lda     #$01
	ldy     #$0D
	sta     (sreg),y
;
; return ret;
;
	.dbg	line, "opendir.c", 37
	ldy     #$03
	jsr     ldaxysp
;
; }
;
	.dbg	line, "opendir.c", 6597632
	jmp     incsp6
	.dbg	line

.endproc

